### ISSUE TITLE
cannot edit path to msys installation

### ISSUE THREAD

**Issue by art0007i** [N00byKing/SM64AP-Launcher#3]
I have msys installed, but not in C:/msys64. The app will not let me type this in though

![image](https://github.com/user-attachments/assets/59674b40-8c1d-4dd2-be66-d08bc6ac2278)

**Comment by art0007i** [comment]
After digging through the source code for a bit I was able to find that there exists an advanced settings checkbox which allows you to type in that field.

I think it would be better if the checkbox to allow editing this field was on the same screen, or even better if it was just not locked behind an advanced settings checkbox, because I don't think this is something that needs to be locked out.

**Comment by N00byKing** [comment]
The reason for that is that msys is quite sensitive to how paths are supposed to look like wrt special characters. As there used to be many bugs reported due to invalid paths set for msys, I am not removing the advanced option requirement for it.

However, you're right in saying that this currently not very intuitive.
I've added a tooltip (hover text) for that textbox that mentions the need to set the checkbox on the main screen.
